# coding: utf-8

# flake8: noqa

"""
    e2a API

    e2a — authenticated email gateway for AI agents. v1 contract.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccountApi",
    "AgentsApi",
    "ConversationsApi",
    "DomainsApi",
    "EventsApi",
    "MessagesApi",
    "MetaApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIKeyExportEntry",
    "AgentIdentity",
    "AgentView",
    "ApproveRequest",
    "ApproveResultView",
    "Attachment",
    "CheckResult",
    "ConversationDetailView",
    "ConversationSummaryView",
    "CreateAgentRequest",
    "CreateAgentResponse",
    "CreateWebhookRequest",
    "DNSRecordView",
    "DNSRecordsView",
    "DeleteAgentOutputBody",
    "DeleteUserDataResult",
    "DeliveryStatusJSON",
    "DeploymentInfoView",
    "Domain",
    "DomainView",
    "ErrorBody",
    "ErrorEnvelope",
    "EventJSON",
    "ForwardRequest",
    "LimitsCapsView",
    "LimitsUsageView",
    "LimitsView",
    "ListAgentsOutputBody",
    "ListDomainsOutputBody",
    "ListWebhooksOutputBody",
    "Message",
    "MessageBodyView",
    "MessageParsedView",
    "MessageSummaryView",
    "MessageView",
    "OAuthConnectionEntry",
    "PageConversationSummaryView",
    "PageEventJSON",
    "PageMessageSummaryView",
    "PageWebhookDeliveryView",
    "RedeliverDelivery",
    "RedeliverEventInputBody",
    "RedeliverView",
    "RegisterDomainRequest",
    "RejectInputBody",
    "RejectResultView",
    "ReplyRequest",
    "Result",
    "RotateSecretOutputBody",
    "SendEmailRequest",
    "SendResultView",
    "SendingDNSRecordView",
    "Suppression",
    "SuppressionsOutputBody",
    "TestWebhookOutputBody",
    "TestWebhookRequest",
    "UpdateAgentRequest",
    "UpdateDomainRequest",
    "UpdateMessageRequest",
    "UpdateMessageResultView",
    "UpdateWebhookRequest",
    "UsageEventEntry",
    "UserExport",
    "UserExportUser",
    "VerifyDomainView",
    "WebhookDeliveryView",
    "WebhookFiltersView",
    "WebhookView",
]

# import apis into sdk package
from e2a.v1.oag.api.account_api import AccountApi as AccountApi
from e2a.v1.oag.api.agents_api import AgentsApi as AgentsApi
from e2a.v1.oag.api.conversations_api import ConversationsApi as ConversationsApi
from e2a.v1.oag.api.domains_api import DomainsApi as DomainsApi
from e2a.v1.oag.api.events_api import EventsApi as EventsApi
from e2a.v1.oag.api.messages_api import MessagesApi as MessagesApi
from e2a.v1.oag.api.meta_api import MetaApi as MetaApi
from e2a.v1.oag.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from e2a.v1.oag.api_response import ApiResponse as ApiResponse
from e2a.v1.oag.api_client import ApiClient as ApiClient
from e2a.v1.oag.configuration import Configuration as Configuration
from e2a.v1.oag.exceptions import OpenApiException as OpenApiException
from e2a.v1.oag.exceptions import ApiTypeError as ApiTypeError
from e2a.v1.oag.exceptions import ApiValueError as ApiValueError
from e2a.v1.oag.exceptions import ApiKeyError as ApiKeyError
from e2a.v1.oag.exceptions import ApiAttributeError as ApiAttributeError
from e2a.v1.oag.exceptions import ApiException as ApiException

# import models into sdk package
from e2a.v1.oag.models.api_key_export_entry import APIKeyExportEntry as APIKeyExportEntry
from e2a.v1.oag.models.agent_identity import AgentIdentity as AgentIdentity
from e2a.v1.oag.models.agent_view import AgentView as AgentView
from e2a.v1.oag.models.approve_request import ApproveRequest as ApproveRequest
from e2a.v1.oag.models.approve_result_view import ApproveResultView as ApproveResultView
from e2a.v1.oag.models.attachment import Attachment as Attachment
from e2a.v1.oag.models.check_result import CheckResult as CheckResult
from e2a.v1.oag.models.conversation_detail_view import ConversationDetailView as ConversationDetailView
from e2a.v1.oag.models.conversation_summary_view import ConversationSummaryView as ConversationSummaryView
from e2a.v1.oag.models.create_agent_request import CreateAgentRequest as CreateAgentRequest
from e2a.v1.oag.models.create_agent_response import CreateAgentResponse as CreateAgentResponse
from e2a.v1.oag.models.create_webhook_request import CreateWebhookRequest as CreateWebhookRequest
from e2a.v1.oag.models.dns_record_view import DNSRecordView as DNSRecordView
from e2a.v1.oag.models.dns_records_view import DNSRecordsView as DNSRecordsView
from e2a.v1.oag.models.delete_agent_output_body import DeleteAgentOutputBody as DeleteAgentOutputBody
from e2a.v1.oag.models.delete_user_data_result import DeleteUserDataResult as DeleteUserDataResult
from e2a.v1.oag.models.delivery_status_json import DeliveryStatusJSON as DeliveryStatusJSON
from e2a.v1.oag.models.deployment_info_view import DeploymentInfoView as DeploymentInfoView
from e2a.v1.oag.models.domain import Domain as Domain
from e2a.v1.oag.models.domain_view import DomainView as DomainView
from e2a.v1.oag.models.error_body import ErrorBody as ErrorBody
from e2a.v1.oag.models.error_envelope import ErrorEnvelope as ErrorEnvelope
from e2a.v1.oag.models.event_json import EventJSON as EventJSON
from e2a.v1.oag.models.forward_request import ForwardRequest as ForwardRequest
from e2a.v1.oag.models.limits_caps_view import LimitsCapsView as LimitsCapsView
from e2a.v1.oag.models.limits_usage_view import LimitsUsageView as LimitsUsageView
from e2a.v1.oag.models.limits_view import LimitsView as LimitsView
from e2a.v1.oag.models.list_agents_output_body import ListAgentsOutputBody as ListAgentsOutputBody
from e2a.v1.oag.models.list_domains_output_body import ListDomainsOutputBody as ListDomainsOutputBody
from e2a.v1.oag.models.list_webhooks_output_body import ListWebhooksOutputBody as ListWebhooksOutputBody
from e2a.v1.oag.models.message import Message as Message
from e2a.v1.oag.models.message_body_view import MessageBodyView as MessageBodyView
from e2a.v1.oag.models.message_parsed_view import MessageParsedView as MessageParsedView
from e2a.v1.oag.models.message_summary_view import MessageSummaryView as MessageSummaryView
from e2a.v1.oag.models.message_view import MessageView as MessageView
from e2a.v1.oag.models.o_auth_connection_entry import OAuthConnectionEntry as OAuthConnectionEntry
from e2a.v1.oag.models.page_conversation_summary_view import PageConversationSummaryView as PageConversationSummaryView
from e2a.v1.oag.models.page_event_json import PageEventJSON as PageEventJSON
from e2a.v1.oag.models.page_message_summary_view import PageMessageSummaryView as PageMessageSummaryView
from e2a.v1.oag.models.page_webhook_delivery_view import PageWebhookDeliveryView as PageWebhookDeliveryView
from e2a.v1.oag.models.redeliver_delivery import RedeliverDelivery as RedeliverDelivery
from e2a.v1.oag.models.redeliver_event_input_body import RedeliverEventInputBody as RedeliverEventInputBody
from e2a.v1.oag.models.redeliver_view import RedeliverView as RedeliverView
from e2a.v1.oag.models.register_domain_request import RegisterDomainRequest as RegisterDomainRequest
from e2a.v1.oag.models.reject_input_body import RejectInputBody as RejectInputBody
from e2a.v1.oag.models.reject_result_view import RejectResultView as RejectResultView
from e2a.v1.oag.models.reply_request import ReplyRequest as ReplyRequest
from e2a.v1.oag.models.result import Result as Result
from e2a.v1.oag.models.rotate_secret_output_body import RotateSecretOutputBody as RotateSecretOutputBody
from e2a.v1.oag.models.send_email_request import SendEmailRequest as SendEmailRequest
from e2a.v1.oag.models.send_result_view import SendResultView as SendResultView
from e2a.v1.oag.models.sending_dns_record_view import SendingDNSRecordView as SendingDNSRecordView
from e2a.v1.oag.models.suppression import Suppression as Suppression
from e2a.v1.oag.models.suppressions_output_body import SuppressionsOutputBody as SuppressionsOutputBody
from e2a.v1.oag.models.test_webhook_output_body import TestWebhookOutputBody as TestWebhookOutputBody
from e2a.v1.oag.models.test_webhook_request import TestWebhookRequest as TestWebhookRequest
from e2a.v1.oag.models.update_agent_request import UpdateAgentRequest as UpdateAgentRequest
from e2a.v1.oag.models.update_domain_request import UpdateDomainRequest as UpdateDomainRequest
from e2a.v1.oag.models.update_message_request import UpdateMessageRequest as UpdateMessageRequest
from e2a.v1.oag.models.update_message_result_view import UpdateMessageResultView as UpdateMessageResultView
from e2a.v1.oag.models.update_webhook_request import UpdateWebhookRequest as UpdateWebhookRequest
from e2a.v1.oag.models.usage_event_entry import UsageEventEntry as UsageEventEntry
from e2a.v1.oag.models.user_export import UserExport as UserExport
from e2a.v1.oag.models.user_export_user import UserExportUser as UserExportUser
from e2a.v1.oag.models.verify_domain_view import VerifyDomainView as VerifyDomainView
from e2a.v1.oag.models.webhook_delivery_view import WebhookDeliveryView as WebhookDeliveryView
from e2a.v1.oag.models.webhook_filters_view import WebhookFiltersView as WebhookFiltersView
from e2a.v1.oag.models.webhook_view import WebhookView as WebhookView

