/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class AgentIdentity {
    'createdAt': Date;
    'domain': string;
    'domainVerified': boolean;
    'email': string;
    'hitlEnabled': boolean;
    'hitlExpirationAction': string;
    'hitlMode': string;
    'hitlTtlSeconds': number;
    'id': string;
    'inbound7d': number;
    'inboundAllowlist'?: Array<string> | null;
    'inboundPolicy': string;
    'lastDeliveryAt'?: Date;
    'name': string;
    'outbound7d': number;
    'pendingCount': number;
    '_public': boolean;
    'userId': string;
    'webhookHealthy': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "domainVerified",
            "baseName": "domain_verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "hitlEnabled",
            "baseName": "hitl_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hitlExpirationAction",
            "baseName": "hitl_expiration_action",
            "type": "string",
            "format": ""
        },
        {
            "name": "hitlMode",
            "baseName": "hitl_mode",
            "type": "string",
            "format": ""
        },
        {
            "name": "hitlTtlSeconds",
            "baseName": "hitl_ttl_seconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "inbound7d",
            "baseName": "inbound_7d",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "inboundAllowlist",
            "baseName": "inbound_allowlist",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "inboundPolicy",
            "baseName": "inbound_policy",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastDeliveryAt",
            "baseName": "last_delivery_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "outbound7d",
            "baseName": "outbound_7d",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pendingCount",
            "baseName": "pending_count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhookHealthy",
            "baseName": "webhook_healthy",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentIdentity.attributeTypeMap;
    }

    public constructor() {
    }
}
