/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Attachment } from '../models/Attachment.js';
import { HttpFile } from '../http/http.js';

export class ApproveRequest {
    'attachments'?: Array<Attachment>;
    'bcc'?: Array<string>;
    'bodyHtml'?: string;
    'bodyText'?: string;
    'cc'?: Array<string>;
    'subject'?: string;
    'to'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<Attachment>",
            "format": ""
        },
        {
            "name": "bcc",
            "baseName": "bcc",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "bodyHtml",
            "baseName": "body_html",
            "type": "string",
            "format": ""
        },
        {
            "name": "bodyText",
            "baseName": "body_text",
            "type": "string",
            "format": ""
        },
        {
            "name": "cc",
            "baseName": "cc",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApproveRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
