/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class ConversationSummaryView {
    'conversationId': string;
    'firstMessageAt': string;
    'hasUnread': boolean;
    'inboundCount': number;
    'lastMessageAt': string;
    'latestSender': string;
    'latestSubject': string;
    'messageCount': number;
    'outboundCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstMessageAt",
            "baseName": "first_message_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasUnread",
            "baseName": "has_unread",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inboundCount",
            "baseName": "inbound_count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "lastMessageAt",
            "baseName": "last_message_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "latestSender",
            "baseName": "latest_sender",
            "type": "string",
            "format": ""
        },
        {
            "name": "latestSubject",
            "baseName": "latest_subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageCount",
            "baseName": "message_count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "outboundCount",
            "baseName": "outbound_count",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ConversationSummaryView.attributeTypeMap;
    }

    public constructor() {
    }
}
