/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class DeliveryStatusJSON {
    'delivered': number;
    'failed': number;
    'matchedWebhooks': number;
    'pending': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "delivered",
            "baseName": "delivered",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "matchedWebhooks",
            "baseName": "matched_webhooks",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return DeliveryStatusJSON.attributeTypeMap;
    }

    public constructor() {
    }
}
