/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DNSRecordView } from '../models/DNSRecordView.js';
import { HttpFile } from '../http/http.js';

export class DNSRecordsView {
    'dkim'?: DNSRecordView;
    'mx': DNSRecordView;
    'txt': DNSRecordView;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dkim",
            "baseName": "dkim",
            "type": "DNSRecordView",
            "format": ""
        },
        {
            "name": "mx",
            "baseName": "mx",
            "type": "DNSRecordView",
            "format": ""
        },
        {
            "name": "txt",
            "baseName": "txt",
            "type": "DNSRecordView",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DNSRecordsView.attributeTypeMap;
    }

    public constructor() {
    }
}
