/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeliveryStatusJSON } from '../models/DeliveryStatusJSON.js';
import { HttpFile } from '../http/http.js';

export class EventJSON {
    'agentId'?: string;
    'conversationId'?: string;
    'createdAt': Date;
    'data': any;
    'deliveryStatus'?: DeliveryStatusJSON;
    'id': string;
    'messageId'?: string;
    'schemaVersion': number;
    'status': string;
    'type': EventJSONTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "agentId",
            "baseName": "agent_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any",
            "format": ""
        },
        {
            "name": "deliveryStatus",
            "baseName": "delivery_status",
            "type": "DeliveryStatusJSON",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaVersion",
            "baseName": "schema_version",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "EventJSONTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventJSON.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum EventJSONTypeEnum {
    EmailReceived = 'email.received',
    EmailSent = 'email.sent',
    EmailPendingApproval = 'email.pending_approval',
    EmailApproved = 'email.approved',
    EmailRejected = 'email.rejected',
    DomainSendingVerified = 'domain.sending_verified',
    DomainSendingFailed = 'domain.sending_failed',
    EmailDelivered = 'email.delivered',
    EmailBounced = 'email.bounced',
    EmailComplained = 'email.complained',
    DomainSuppressionAdded = 'domain.suppression_added',
    EmailFlagged = 'email.flagged'
}

