/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebhookView } from '../models/WebhookView.js';
import { HttpFile } from '../http/http.js';

export class ListWebhooksOutputBody {
    'webhooks': Array<WebhookView> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "webhooks",
            "baseName": "webhooks",
            "type": "Array<WebhookView>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListWebhooksOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
