/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class RedeliverEventInputBody {
    'webhookId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "webhookId",
            "baseName": "webhook_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RedeliverEventInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
