/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class UpdateAgentRequest {
    'hitlEnabled'?: boolean;
    'hitlExpirationAction'?: string;
    'hitlMode'?: string;
    'hitlTtlSeconds'?: number;
    'inboundAllowlist'?: Array<string>;
    'inboundPolicy'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hitlEnabled",
            "baseName": "hitl_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hitlExpirationAction",
            "baseName": "hitl_expiration_action",
            "type": "string",
            "format": ""
        },
        {
            "name": "hitlMode",
            "baseName": "hitl_mode",
            "type": "string",
            "format": ""
        },
        {
            "name": "hitlTtlSeconds",
            "baseName": "hitl_ttl_seconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "inboundAllowlist",
            "baseName": "inbound_allowlist",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "inboundPolicy",
            "baseName": "inbound_policy",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateAgentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
