/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebhookFiltersView } from '../models/WebhookFiltersView.js';
import { HttpFile } from '../http/http.js';

export class WebhookView {
    'autoDisabledAt'?: string;
    'createdAt': string;
    'description': string;
    'enabled': boolean;
    'events': Array<string> | null;
    'filters': WebhookFiltersView;
    'id': string;
    'lastDeliveredAt'?: string;
    'previousSecretExpiresAt'?: string;
    'signingSecret'?: string;
    'url': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "autoDisabledAt",
            "baseName": "auto_disabled_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "WebhookFiltersView",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastDeliveredAt",
            "baseName": "last_delivered_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousSecretExpiresAt",
            "baseName": "previous_secret_expires_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "signingSecret",
            "baseName": "signing_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebhookView.attributeTypeMap;
    }

    public constructor() {
    }
}
