/**
 * e2a API
 * e2a — authenticated email gateway for AI agents. v1 contract.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class WebhookDeliveryView {
    'attempts': number;
    'createdAt': string;
    'eventType': WebhookDeliveryViewEventTypeEnum;
    'id': string;
    'lastAttemptAt'?: string;
    'lastError'?: string;
    'lastStatusCode'?: number;
    'nextRetryAt': string;
    'status': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attempts",
            "baseName": "attempts",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "WebhookDeliveryViewEventTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastAttemptAt",
            "baseName": "last_attempt_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastError",
            "baseName": "last_error",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastStatusCode",
            "baseName": "last_status_code",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "nextRetryAt",
            "baseName": "next_retry_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebhookDeliveryView.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum WebhookDeliveryViewEventTypeEnum {
    EmailReceived = 'email.received',
    EmailSent = 'email.sent',
    EmailPendingApproval = 'email.pending_approval',
    EmailApproved = 'email.approved',
    EmailRejected = 'email.rejected',
    DomainSendingVerified = 'domain.sending_verified',
    DomainSendingFailed = 'domain.sending_failed',
    EmailDelivered = 'email.delivered',
    EmailBounced = 'email.bounced',
    EmailComplained = 'email.complained',
    DomainSuppressionAdded = 'domain.suppression_added',
    EmailFlagged = 'email.flagged'
}

