# coding: utf-8

"""
    e2a API

    e2a — authenticated email gateway for AI agents. v1 contract.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Domain(BaseModel):
    """
    Domain
    """ # noqa: E501
    agent_count: StrictInt
    created_at: datetime
    dkim_public_key: Optional[StrictStr] = None
    dkim_selector: Optional[StrictStr] = None
    domain: StrictStr
    is_primary: StrictBool
    last_checked_at: Optional[datetime] = None
    sending_error: Optional[StrictStr] = None
    sending_last_checked_at: Optional[datetime] = None
    sending_status: StrictStr
    user_id: Optional[StrictStr] = None
    verification_token: StrictStr
    verified: StrictBool
    verified_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["agent_count", "created_at", "dkim_public_key", "dkim_selector", "domain", "is_primary", "last_checked_at", "sending_error", "sending_last_checked_at", "sending_status", "user_id", "verification_token", "verified", "verified_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Domain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Domain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_count": obj.get("agent_count"),
            "created_at": obj.get("created_at"),
            "dkim_public_key": obj.get("dkim_public_key"),
            "dkim_selector": obj.get("dkim_selector"),
            "domain": obj.get("domain"),
            "is_primary": obj.get("is_primary"),
            "last_checked_at": obj.get("last_checked_at"),
            "sending_error": obj.get("sending_error"),
            "sending_last_checked_at": obj.get("sending_last_checked_at"),
            "sending_status": obj.get("sending_status"),
            "user_id": obj.get("user_id"),
            "verification_token": obj.get("verification_token"),
            "verified": obj.get("verified"),
            "verified_at": obj.get("verified_at")
        })
        return _obj


