# coding: utf-8

"""
    e2a API

    e2a — authenticated email gateway for AI agents. v1 contract.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from e2a.v1.oag.models.attachment import Attachment
from typing import Optional, Set
from typing_extensions import Self

class SendEmailRequest(BaseModel):
    """
    SendEmailRequest
    """ # noqa: E501
    attachments: Optional[List[Attachment]] = None
    bcc: Optional[List[StrictStr]] = None
    body: Optional[StrictStr] = None
    cc: Optional[List[StrictStr]] = None
    conversation_id: Optional[StrictStr] = None
    var_from: Optional[StrictStr] = Field(default=None, alias="from")
    html_body: Optional[StrictStr] = None
    subject: Optional[StrictStr] = None
    to: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["attachments", "bcc", "body", "cc", "conversation_id", "from", "html_body", "subject", "to"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendEmailRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # set to None if attachments (nullable) is None
        # and model_fields_set contains the field
        if self.attachments is None and "attachments" in self.model_fields_set:
            _dict['attachments'] = None

        # set to None if bcc (nullable) is None
        # and model_fields_set contains the field
        if self.bcc is None and "bcc" in self.model_fields_set:
            _dict['bcc'] = None

        # set to None if cc (nullable) is None
        # and model_fields_set contains the field
        if self.cc is None and "cc" in self.model_fields_set:
            _dict['cc'] = None

        # set to None if to (nullable) is None
        # and model_fields_set contains the field
        if self.to is None and "to" in self.model_fields_set:
            _dict['to'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendEmailRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attachments": [Attachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "bcc": obj.get("bcc"),
            "body": obj.get("body"),
            "cc": obj.get("cc"),
            "conversation_id": obj.get("conversation_id"),
            "from": obj.get("from"),
            "html_body": obj.get("html_body"),
            "subject": obj.get("subject"),
            "to": obj.get("to")
        })
        return _obj


